font=Noto Sans
use-bold=yes

prompt=">  "
show-actions=yes
match-mode=fuzzy
match-counter=yes

terminal=uwsm-app -T --
launch-prefix=uwsm-app --

horizontal-pad=25
x-margin=3
y-margin=3

layer=overlay
exit-on-keyboard-focus-loss=no

# Catppuccin Macchiato
[colors]
background=24273a88
text=cad3f5ff
prompt=b8c0e0ff
placeholder=8087a2ff
input=cad3f5ff
match=7dc4e4ff
selection=494d64aa
selection-text=cad3f5ff
selection-match=7dc4e4ff
counter=8087a2ff
border=7dc4e4ff

[border]
radius=17
width=2
selection-radius=5

[dmenu]
exit-immediately-if-empty=yes

[key-bindings]
execute-input=Control+Return

cursor-left=Left Control+b Mod1+h
cursor-right=Right Control+f Mod1+l
cursor-left-word=Control+Left Mod1+b
cursor-right-word=Control+Right Mod1+f Mod1+w Mod1+e
cursor-home=Home Control+a
cursor-end=End Control+e

next=none
prev=none
next-with-wrap=Down Control+n Mod1+j
prev-with-wrap=Up Control+p Mod1+k
next-page=Page_Down Control+d Mod1+l
prev-page=Page_Up Control+u Mod1+h
first=Control+Home Mod1+g
last=Control+End Mod1+G
