#!/usr/bin/env sh

hyprctl reload
kill $(pgrep -u $USER waybar); setsid waybar >/dev/null 2>&1 < /dev/null &
kill $(pgrep -u $USER dunst); setsid dunst >/dev/null 2>&1 < /dev/null &
kill $(pgrep -u $USER fusuma); setsid fusuma >/dev/null 2>&1 < /dev/null &

