#!/usr/bin/env sh

# ==== Usage ====
USAGE="
Usage: $0 [OPTION] [FILE]
       $0 -h

ARGUMENTS
    FILE            The file to parse. If not set or '-', read form stdin.

OPTIONS
    -m, --mode MODE
                    Set mode (valid modes: 'sh', 'git')
    -h, --help      Show this message
"
Help() { echo "$USAGE"; }

# ==== Specifics ====
# ---- Constants ----
ABBR_MARKER="#abbr"

# ---- Functions ----
get_abbr_lines() {
    grep "$ABBR_MARKER" "$@"
}

parse_abbr_sh() {
    sed -E "s/^\s*alias ([^=]+)='([^']+)'.*/abbr \"\1\"=\"\2\"/"
}

parse_abbr_git() {
    echo "Error: git parse not implemented" >&2
    return 1
}

# ==== Main flow ====

# Options and defaults
MODE=sh

# ---- Args ----
while true; do
    case "$1" in
        -h | --help ) Help;  exit 0;;
        -m | --mode ) MODE="${2?Fatal: '-m' requires a mode}"; shift;;
        -* )          echo "Fatal: unknown option '$1'" >&2; exit 1;;
        -- )          shift; break;;
        * )           break;;
    esac
    shift
done
[ "$#" -eq 0 ] && set -- '-' # No args fallback to '-'
# Files in "$@"

case "$MODE" in
    sh )  get_abbr_lines "$@" | parse_abbr_sh ;;
    git ) get_abbr_lines "$@" | parse_abbr_git ;;
    * )   echo "Fatal: unknown mode '$MODE'"; exit 1;;
esac
