#!/usr/bin/env bash

echo_help() {
    echo "Usage: logcmd [flags] <filename> <command>"
    echo "  Flags:"
    echo "   -c  --clear   Clear file before writing"
    echo "   -h  --help    Show this message"
}

CLEAR=0

case "$1" in
    -c | --clear)
        CLEAR=1
        shift;;
    -h | --help)
        echo_help
        exit 0;;
esac

if [[ -n "$1" && "$1" != -* ]]; then
    FILE="$1"
    shift
else
    echo_help
    exit 1
fi

if [ $CLEAR -eq 1 ]; then
    > $FILE
fi

echo "[$(date '+%Y-%m-%d, %T')] ${@:1}" >> $FILE
${@:1} 2>&1 | tee -a $FILE

