swipe:
  3:
    up:
      command: "hyprctl dispatch workspace +1"
    down:
      command: "hyprctl dispatch workspace -1"
    left:
      command: "hyprctl dispatch sendshortcut CTRL, Tab, activewindow"
    right:
      command: "hyprctl dispatch sendshortcut CTRL SHIFT, Tab, activewindow"
  4:
    up:
      update:
        command: "~/.scripts/system/volume_ctl.sh -i 5"
        interval: 0.5
    down:
      update:
        command: "~/.scripts/system/volume_ctl.sh -d 5"
        interval: 0.5
    left:
      command: "playerctl next"
    right:
      command: "playerctl previous"

hold:
  2:
    command: "~/.scripts/system/volume_ctl.sh -t"
  3:
    command: "hyprctl dispatch sendshortcut , F5, activewindow"
  4:
    command: "playerctl play-pause"

rotate:
  3:
    clockwise:
      update:
        command: "~/.scripts/system/volume_ctl.sh -i 5"
        interval: 0.5
    counterclockwise:
      update:
        command: "~/.scripts/system/volume_ctl.sh -d 5"
        interval: 0.5
  4:
    clockwise:
      update:
        command: "~/.scripts/system/brightness_ctl.sh s 10%+"
        interval: 0.5
    counterclockwise:
      update:
        command: "~/.scripts/system/brightness_ctl.sh s 10%-"
        interval: 0.5

