try_source() { [[ -f "$1" ]] && source "$1"; }

# Environment vars
try_source "${XDG_CONFIG_HOME:-$HOME/.config}/shell/env.sh"

# Do nothing if not interactive
case $- in
    *i*) ;;
    *)   return;;
esac

# If we can run zsh, then do it. Drop back to bash on non-0 exit.
if command -v zsh >/dev/null 2>&1; then
    zsh && exit 0
fi

export HISTFILE="${XDG_STATE_HOME:-$HOME/.local/state}/bash/history"

# Synth Shell
# try_source ~/.config/synth-shell/synth-shell-greeter.sh
try_source ~/.config/synth-shell/synth-shell-prompt.sh
# try_source ~/.config/synth-shell/better-ls.sh
# try_source ~/.config/synth-shell/alias.sh
try_source ~/.config/synth-shell/better-history.sh

# Alias
try_source "~/.config/shell/alias.sh"

# Init
eval "$(zoxide init bash --cmd cd)"
try_source ~/.fzf.bash || eval "$(fzf --bash)"
try_source /usr/share/git/completion/git-completion.bash

# Should be set by services and the Desktop Environment. It can fuck shit up in cases like Agent Forwarding
# export SSH_AUTH_SOCK=$XDG_RUNTIME_DIR/ssh-agent.socket

# ==== yazi ====
try_source ~/.scripts/rc/yazi_quitcd.sh

# ==== nnn ====
try_source ~/.scripts/rc/nnn_quitcd.sh
# export NNN_OPTS="aAcEGHiQRux" # Must be compiled with O_GITSTATUS=1
export NNN_OPTS="aAcEHiQRux"
export NNN_TRASH=2
export NNN_PLUG="v:-preview-tui;e:-!echo $nnn|wl-copy*;c:-!echo $PWD/$nnn|wl-copy*"

#####################
## LOCAL OVERRIDES ##
#####################

try_source "${XDG_CONFIG_HOME:-$HOME/.config}/bash/bashrc_local"
try_source ~/.bashrc_local
