#!/usr/bin/env bash

# Check for batctl existence
if ! command -v dconf >/dev/null; then
    echo "Fatal: Couldn't find dconf." >&2
    exit 1
fi

# ==== Usage ====
USAGE="
$0 - Switch for gnome color scheme via dconf
Usage: $0 [OPTIONS] [COMMAND]
       $0 -h

OPTIONS:

    -h, --help      Show this message
    -j, --json      Output custom JSON

See 'batctl --help'
"

function Help() {
    echo "$USAGE"
}

# ==== Constants ====

DCONF_PATH="/org/gnome/desktop/interface/color-scheme"

ICON_SUN=" "
ICON_MOON="  "
ICON_FORBID=" "
# hair space: " "; thin space: " "

# ==== Functions ====

get_mode() {
    dconf read "$DCONF_PATH" | sed "s/'//g"
}

get_toggle() {
    case "$(get_mode)" in
        prefer-dark ) echo "prefer-light";;
        * )           echo "prefer-dark";;
    esac
}

print_info() {
    mode="$(get_mode)"
    case "$mode" in
        prefer-dark )  icon="$ICON_MOON";;
        prefer-light ) icon="$ICON_SUN";;
        default )      icon="$ICON_FORBID";;
    esac

    if [ "$JSON" -eq 1 ]; then
        jq -n --unbuffered --compact-output \
            --arg text "$icon" \
            --arg status "$mode" \
            --arg tooltip "Theme: $mode" \
            '{
                "text": $text, "alt": $status,
                "tooltip": $tooltip, "class": $status
            }'
    else
        echo "$mode"
    fi
}


# ==== Main ====

# ---- Globals ----
SET=
JSON=0

# ---- Args ----
case "$1" in
    -h | --help )
        Help
        exit 0;;
    -j | --json )
        JSON=1
        shift;;
esac

case "$1" in
    toggle ) SET="$(get_toggle)";;
    set )    SET="${2:?"Missing value for '$1'"}";;
esac

[ -n "$SET" ] && dconf write "$DCONF_PATH" "'$SET'"
[ -n "$SET" ] && echo dconf write "$DCONF_PATH" "'$SET'"

print_info
