#############
### INPUT ###
#############

# https://wiki.hyprland.org/Configuring/Variables/#input
input {
    # Be sure to check out xkb setup
    kb_layout = es
    kb_variant =
    kb_model =
    kb_options = eurosign:5,altgreek,undead:es_only,altmath,caps:escape_shifted_capslock
    kb_rules =

    numlock_by_default = true

    follow_mouse = 2

    sensitivity = -0.2 # -1.0 - 1.0, 0 means no modification.
    accel_profile = custom
    scroll_points = 0.2144477506 0.000 0.307 0.615 1.077 1.539 2.002 2.505 3.208 3.910 4.613 5.315 6.018 6.720 7.423 8.125 8.828 9.530 10.233 10.935 12.387

    touchpad {
        natural_scroll = true
        scroll_factor = 0.2
    }
}

## DEVICES ##

device {
    name = elan0518:01-04f3:31fc-touchpad
    sensitivity = 0.2
}

device {
    name = logitech-gaming-mouse-g402
    sensitivity = -0.8
}

device {
    name = dell-computer-corp-dell-universal-receiver-mouse
    sensitivity = -0.8
}

device {
    name = logitech-optical-usb-mouse
    sensitivity = 0.5
}
