# Kitty advanced config
# See kitty.conf(5)

# ==== Advanced ============================================

#shell .
#editor .

#close_on_child_death no

#remote_control_password
# Possible values: password, socket-only, socket, no, yes
allow_remote_control socket
listen_on unix:kitty

#env

#watcher

#exe_search_path

#update_check_interval 24

#startup_session none

#clipboard_control write-clipboard write-primary read-clipboard-ask read-primary-ask

#clipboard_max_size 512

#file_transfer_confirmation_bypass

#allow_hyperlinks yes

#shell_integration enabled

#allow_cloning ask

# Supported strategies: venv, conda, env_var, path
#clone_source_strategies venv,conda,env_var,path

# Needs shell_integration. Possible values: never, unfocused, invisible,
# always. Optional arguments are [duration] and [action], where action is one
# of notify, bell, command
#notify_on_cmd_finish never

#term xterm-kitty
#terminfo_type path

#forward_stdio no

#menu_map
