# Kitty display config
# See kitty.conf(5)

# ==== Display =============================================

background_opacity 0.7
#background_blur 0

#background_image none
#background_image_layout tiled
#background_image_linear no

#dynamic_background_opacity no

#background_tint 0.0
#background_tint_gaps 1.0

#dim_opacity 0.4
