# Kitty fonts config
# See kitty.conf(5)

# ==== Fonts ===============================================

# ---- Font family, style and size ---------------
font_family      family="Fira Code" style="Retina"
bold_font        family="Fira Code" style="Bold"
# Italic Fira Mono from https://github.com/Avi-D-coder/fira-mono-italic
italic_font      family="Fira Mono" style="Regular Italic"
bold_italic_font family="Fira Mono" style="Bold Italic"

font_size 11.0

# ---- Font features and ligatures ---------------

disable_ligatures cursor

# E.g.:
#     font_features FiraCode-Retina +zero +onum
#     font_features TT2020StyleB-Regular -liga +calt
#     font_features UnifontMedium +isol -medi -fina -init
# or
#     font_features none
font_features FiraCode-Retina  +calt
    \ +cv01 +cv02 +cv06 -cv10 +ss01 -ss10
    \ +zero +cv15 +cv18 +ss02 +ss03 +ss04 -ss05 +ss06 +ss07
    \ +zero +cv15 +cv18 +ss02 +ss03 +ss04 -ss05 +ss06 +ss07
#   \ +cv20 -ss02

font_features FiraCode-Regular +calt
    \ +cv01 +cv02 +cv06 -cv10 +ss01 -ss10
    \ +zero +cv15 +cv18 +ss02 +ss03 +ss04 -ss05 +ss06 +ss07
#   \ +cv20 -ss02

font_features FiraCode-Bold    +calt
    \ +cv01 +cv02 +cv06 -cv10 +ss01 -ss10
    \ +zero +cv15 +cv18 +ss02 +ss03 +ss04 -ss05 +ss06 +ss07
#   \ +cv20 -ss02


# ---- Font drawing options ----------------------

# E.g.:
#     modify_font underline_position -2
#     modify_font underline_thickness 150%
#     modify_font strikethrough_position 2px
# or
#     modify_font cell_width 100%
#     modify_font cell_height -2px
#     modify_font baseline -1
modify_font cell_width 100%

#box_drawing_scale 0.001, 1, 1.5, 2
#undercurl_style thin-sparse
#text_composition_strategy platform
#text_fg_override_threshold 0

# ---- Unusual font options ----------------------
#force_ltr no

# Syntax: symbol_map codepoints Font Family Name
# E.g.: symbol_map U+E0A0-U+E0A3,U+E0C0-U+E0C7 PowerlineSymbols
#symbol_map

# Syntax: narrow_symbols codepoints [number of cells]
# This option can be specified multiple times.
# E.g. narrow_symbols U+E0A0-U+E0A3,U+E0C0-U+E0C7 1
#narrow_symbols
