# See kitty.conf(5)

include fonts.conf
include cursor.conf
include scrollback.conf
include mouse.conf
include performance.conf
include bell.conf
include window.conf
include tabbar.conf
include display.conf
include theme.conf
include advanced.conf
include tweaks.conf
include map.conf

# Inlcude drop-in config files in the kitty config dir
globinclude *.d.conf
