# Kitty mouse config
# See kitty.conf(5)

# ==== Mouse ===============================================

#mouse_hide_wait 3.0

#url_color #0087bd

# Can be one of: none, straight, double, curly, dotted, dashed.
#url_style curly

#open_url_with default

url_prefixes file ftp ftps gemini git gopher http https irc ircs kitty mailto news sftp ssh
detect_urls yes
#url_excluded_characters
#show_hyperlink_targets no
#underline_hyperlinks hover

#copy_on_select no

# Actions to take when pasting. Supports: quote-urls-at-prompt,
# replace-dangerous-control-codes, replace-newline, confirm, confirm-if-large,
# filter, no-op
#paste_actions quote-urls-at-prompt,confirm

#strip_trailing_spaces never

#select_by_word_characters @-./_~?&=%+#
# If empty (default) select_by_word_characters will be used
#select_by_word_characters_forward

#click_interval -1.0

#focus_follows_mouse no

#pointer_shape_when_grabbed arrow
#default_pointer_shape beam
#pointer_shape_when_dragging beam

# ---- Mouse actions -----------------------------

#clear_all_mouse_actions no

# Remove all mouse action definitions up to this point. Useful, for
# instance, to remove the default mouse actions.

# Click the link under the mouse or move the cursor (shell integration)
#mouse_map left click ungrabbed mouse_handle_click selection link prompt

# Click the link under the mouse or move the cursor even when grabbed (shell
# integration)
#mouse_map shift+left click grabbed,ungrabbed mouse_handle_click selection link
#prompt

# Click the link under the mouse cursor (shell integration)
#mouse_map ctrl+shift+left release grabbed,ungrabbed mouse_handle_click link

# Discard press event for link click
#mouse_map ctrl+shift+left press grabbed discard_event

# Paste from the primary selection
#mouse_map middle release ungrabbed paste_from_selection

# Start selecting text
#mouse_map left press ungrabbed mouse_selection normal

# Start selecting text in a rectangle
mouse_map alt+shift+left press ungrabbed mouse_selection rectangle

# Select a word
mouse_map left doublepress ungrabbed mouse_selection word

# Select a line
mouse_map left triplepress ungrabbed mouse_selection line

# Select line from point
#mouse_map ctrl+alt+left triplepress ungrabbed mouse_selection line_from_point

# Extend the current selection
#mouse_map right press ungrabbed mouse_selection extend

# Paste from the primary selection even when grabbed
#mouse_map shift+middle release ungrabbed,grabbed paste_selection
#mouse_map shift+middle press grabbed discard_event

# Start selecting text even when grabbed
#mouse_map shift+left press ungrabbed,grabbed mouse_selection normal

# Start selecting text in a rectangle even when grabbed
#mouse_map ctrl+shift+alt+left press ungrabbed,grabbed mouse_selection rectangle

# Select a word even when grabbed
#mouse_map shift+left doublepress ungrabbed,grabbed mouse_selection word

# Select a line even when grabbed
#mouse_map shift+left triplepress ungrabbed,grabbed mouse_selection line

# Select line from point even when grabbed
#mouse_map ctrl+shift+alt+left triplepress ungrabbed,grabbed mouse_selection line_from_point

# Extend the current selection even when grabbed
#mouse_map shift+right press ungrabbed,grabbed mouse_selection extend

# Show clicked command output in pager (shell integration)
#mouse_map ctrl+shift+right press ungrabbed mouse_show_command_output
