swipe:
  3:
    up:
      command: "hyprctl dispatch workspace previous"
    down:
      command: "hyprctl dispatch togglespecialworkspace tmp"
    left:
      command: "hyprctl dispatch sendshortcut CTRL, Tab, activewindow"
    right:
      command: "hyprctl dispatch sendshortcut CTRL SHIFT, Tab, activewindow"
  4:
    up:
      update:
        command: "~/.scripts/system/volume_ctl.sh -i 2"
        interval: 0.2
        threshold: 0.6
    down:
      update:
        command: "~/.scripts/system/volume_ctl.sh -d 2"
        interval: 0.2
        threshold: 0.6
    left:
      command: "playerctl next"
    right:
      command: "playerctl previous"

hold:
  # 2:
    # command: "~/.scripts/system/volume_ctl.sh -t"
  3:
    command: "~/.scripts/system/volume_ctl.sh -t"
    # command: "hyprctl dispatch sendshortcut , F5, activewindow"
  4:
    command: "playerctl play-pause"

rotate:
  3:
    clockwise:
      update:
        command: "~/.scripts/system/volume_ctl.sh -i 5"
        interval: 0.8
        threshold: 0.6
    counterclockwise:
      update:
        command: "~/.scripts/system/volume_ctl.sh -d 5"
        interval: 0.8
        threshold: 0.6
  4:
    clockwise:
      update:
        command: "~/.scripts/system/brightness_ctl.sh s 10%+"
        interval: 0.8
        threshold: 0.6
    counterclockwise:
      update:
        command: "~/.scripts/system/brightness_ctl.sh s 10%-"
        interval: 0.8
        threshold: 0.6

