set-option -g mouse on
set-window-option -g mode-keys vi

# Please let me have colors
set-option -g default-terminal "tmux-256color"
set -as terminal-overrides ",xterm*:Tc"

# Send escape more quickly. Before this timeout, escape and the following key
# are sent together (Alt+key behavior).
set-option -g escape-time 10

# Way more comfortable than C-b, but let's allow both
set-option -g prefix2 M-a
bind-key M-a send-prefix

bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
# # Linux
# set -s copy-command 'xclip -in -selection clipboard'
# bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# Moving through windows
bind-key -T prefix h select-window -p
bind-key -T prefix l select-window -n
bind-key -T prefix H swap-window -t +
bind-key -T prefix L swap-window -t -
# Moving through panes
bind-key -T prefix j select-pane -t +
bind-key -T prefix k select-pane -t -
bind-key -T prefix J swap-pane -t +
bind-key -T prefix K swap-pane -t -

# Redraw
bind-key -T prefix C-l refresh
